### ISSUE TITLE
About student class 

### ISSUE THREAD

**Issue by ak-seyam** [abdo1819/projects_gallary#1]
**student** shouldn't have a particular **group** property [a list of groups could be fine] but i can't see a reason for this property at all

suggested scenario: 
presenting a project with **[made by: $Group_name]** label will be more than enough for me
if the guest need more info he should click group's name to find out more

**Comment by abdo1819** [comment]
* it is just a misunderstand group here only represent the (فرقة ) not a mean that those student are in same group at project 

 * `[a list of groups could be fine] ` this is not even required as project has many to many relation with student so groups can easily be deduce from that 
* `presenting a project with [made by: $Group_name] label will be more than enough for me
if the guest need more info he should click group's name to find out more`
i don't think students have to name their groups as from our experience that students are not always together in different projects especially that most of them are related to collage materials

> but it is a good idea we can add groups later for free projects or we like creating competition
